import React from 'react'

const EntityExtForm: React.FC = () => (
  // const renderFormComponent = (field = typeof ComponentInfoSample[0]) => {
  //   if (field.Id === 'TextField') {}
  //   switch(true) {
  //     case true:

  //   }
  // }

  <div>EntityExtForm !!!</div>
)

export default EntityExtForm

// const FormElements = {
//   TextField: <div>TextField !!!</div>,
//   TextArea: <div>TextArea !!!</div>,
//   Checkbox: <div>Checkbox !!!</div>,
//   CheckboxGroup: <div>CheckboxGroup !!!</div>,
//   DateField: <div>DateField !!!</div>,
// }

// type ComponentClass = 'MA_TextField' | 'MA_TextArea' | 'MA_Checkbox' | 'MA_CheckboxGroup' | 'MA_DateField'

// const ComponentInfoSample = [
//   {
//     ExId: 4,
//     ItemId: 14588,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_TextField',
//     Config: '{"label":"Short anser"}',
//     FieldId: 12426,
//     Sequence: 1,
//     SyncGuid: '4B29AA83-3835-4103-95CA-B3E53DF85034',
//     $index: 0,
//   },
//   {
//     ExId: 4,
//     ItemId: 14587,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_TextArea',
//     Config: '{"label":"paragraph"}',
//     FieldId: 12427,
//     Sequence: 2,
//     SyncGuid: 'DD039BBA-20F0-438C-A722-5E91271B40A4',
//     $index: 1,
//   },
//   {
//     ExId: 4,
//     ItemId: 14586,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_NumberField',
//     Config: '{"label":"Number"}',
//     FieldId: 12428,
//     Sequence: 3,
//     SyncGuid: '286B120D-3073-495A-9953-610E053E0F00',
//     $index: 2,
//   },
//   {
//     ExId: 4,
//     ItemId: 14585,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_CheckboxGroup',
//     Config: '{"label":"Checkbox group","type":"checkbox"}',
//     FieldId: 12429,
//     Sequence: 4,
//     SyncGuid: '80E7527D-D3A8-4FD7-B292-4F7C95830E38',
//     $index: 3,
//   },
//   {
//     ExId: 4,
//     ItemId: 14584,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_CheckboxGroup',
//     Config: '{"label":"Multiple choice","type":"radio"}',
//     FieldId: 12430,
//     Sequence: 5,
//     SyncGuid: '2F965839-391D-415E-8D12-C1766D5DA6D4',
//     $index: 4,
//   },
//   {
//     ExId: 4,
//     ItemId: 14583,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_ListField',
//     Config: '{"label":"Dropdown"}',
//     FieldId: 12431,
//     Sequence: 6,
//     SyncGuid: '1D6AE8A3-6401-4A4D-AC42-1B103871EBD1',
//     $index: 5,
//   },
//   {
//     ExId: 4,
//     ItemId: 14582,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_DateField',
//     Config: '{"label":"Date"}',
//     FieldId: 12432,
//     Sequence: 7,
//     SyncGuid: '9CAD8662-95E1-4571-8673-F004F413A838',
//     $index: 6,
//   },
//   {
//     ExId: 4,
//     ItemId: 14581,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_Checkbox',
//     Config: '{"label":"Checkbox"}',
//     FieldId: 12433,
//     Sequence: 8,
//     SyncGuid: '61E62702-70A5-4520-A833-37DBA156B444',
//     $index: 7,
//   },
//   {
//     ExId: 4,
//     ItemId: 14580,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_ListField',
//     Config:
//       '{"fieldSize":"small","data":[{"name":"yes","value":1,"cap":"Yes"},{"name":"no","value":0,"cap":"No"}],"displayField":"cap","valueField":"value","label":"Yes no"}',
//     FieldId: 12434,
//     Sequence: 9,
//     SyncGuid: '1014D5C1-0239-4421-AB4B-11370E36C7CC',
//     $index: 8,
//   },
//   {
//     ExId: 4,
//     ItemId: 14579,
//     ParentId: 14578,
//     Name: null,
//     Class: 'MA_ListField',
//     Config:
//       '{"fieldSize":"small","data":[{"name":"Yes","value":"Yes","cap":"Yes"},{"name":"No","value":"No","cap":"No"}],"displayField":"cap","valueField":"value","isNonBooleanYN":true,"label":"Yes - no non boolean"}',
//     FieldId: 12435,
//     Sequence: 10,
//     SyncGuid: '9FADE44A-514E-4BC0-B9E6-61122A8E2730',
//     $index: 9,
//   },
// ] as const

// const ComponentDataSample = [
//   {
//     ExId: 4,
//     Id: 12426,
//     FieldSetId: 0,
//     Name: 'Short anser',
//     Caption: 'Short anser',
//     Description: '',
//     IsMultiValue: false,
//     Type: 5,
//     AllowedValuesInterface: [],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: '38F295C4-94B6-495E-B59E-7AAC6A54A752',
//   },
//   {
//     ExId: 4,
//     Id: 12427,
//     FieldSetId: 0,
//     Name: 'paragraph',
//     Caption: 'paragraph',
//     Description: '',
//     IsMultiValue: false,
//     Type: 6,
//     AllowedValuesInterface: [],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: '1830E65D-7F94-4081-AEA1-6DDCB7349482',
//   },
//   {
//     ExId: 4,
//     Id: 12428,
//     FieldSetId: 0,
//     Name: 'Number',
//     Caption: 'Number',
//     Description: '',
//     IsMultiValue: false,
//     Type: 0,
//     AllowedValuesInterface: [],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: 'AAA789FC-277D-42E5-A4F6-0DA32263C7AE',
//   },
//   {
//     ExId: 4,
//     Id: 12429,
//     FieldSetId: 0,
//     Name: 'Checkbox group',
//     Caption: 'Checkbox group',
//     Description: '',
//     IsMultiValue: true,
//     Type: 6,
//     AllowedValuesInterface: [
//       {
//         FieldId: 12429,
//         Key: '1',
//         Value: 'Option 1',
//         Caption: 'Option 1',
//         Description: '',
//         Lang: 'en',
//         Sequence: 1,
//       },
//       {
//         FieldId: 12429,
//         Key: '2',
//         Value: 'Option 2',
//         Caption: 'Option 2',
//         Description: '',
//         Lang: 'en',
//         Sequence: 2,
//       },
//       {
//         FieldId: 12429,
//         Key: '3',
//         Value: 'Option 3',
//         Caption: 'Option 3',
//         Description: '',
//         Lang: 'en',
//         Sequence: 3,
//       },
//     ],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: 'D8C4603B-7383-4441-B30C-D852C6D66387',
//   },
//   {
//     ExId: 4,
//     Id: 12430,
//     FieldSetId: 0,
//     Name: 'Multiple choice',
//     Caption: 'Multiple choice',
//     Description: '',
//     IsMultiValue: true,
//     Type: 6,
//     AllowedValuesInterface: [
//       {
//         FieldId: 12430,
//         Key: '1',
//         Value: 'Option 1',
//         Caption: 'Option 1',
//         Description: '',
//         Lang: 'en',
//         Sequence: 1,
//       },
//       {
//         FieldId: 12430,
//         Key: '2',
//         Value: 'Option 2',
//         Caption: 'Option 2',
//         Description: '',
//         Lang: 'en',
//         Sequence: 2,
//       },
//       {
//         FieldId: 12430,
//         Key: '3',
//         Value: 'Option 3',
//         Caption: 'Option 3',
//         Description: '',
//         Lang: 'en',
//         Sequence: 3,
//       },
//     ],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: 'CA2B0164-6423-4B2E-A349-AB0B112E1D86',
//   },
//   {
//     ExId: 4,
//     Id: 12431,
//     FieldSetId: 0,
//     Name: 'Dropdown',
//     Caption: 'Dropdown',
//     Description: '',
//     IsMultiValue: false,
//     Type: 6,
//     AllowedValuesInterface: [
//       {
//         FieldId: 12431,
//         Key: '1',
//         Value: 'Option 1',
//         Caption: 'Option 1',
//         Description: '',
//         Lang: 'en',
//         Sequence: 1,
//       },
//       {
//         FieldId: 12431,
//         Key: '2',
//         Value: 'Option 2',
//         Caption: 'Option 2',
//         Description: '',
//         Lang: 'en',
//         Sequence: 2,
//       },
//       {
//         FieldId: 12431,
//         Key: '3',
//         Value: 'Option 3',
//         Caption: 'Option 3',
//         Description: '',
//         Lang: 'en',
//         Sequence: 3,
//       },
//       {
//         FieldId: 12431,
//         Key: '4',
//         Value: 'Option 4',
//         Caption: 'Option 4',
//         Description: '',
//         Lang: 'en',
//         Sequence: 4,
//       },
//     ],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: '554E3718-3E2B-4047-9AC0-B01A47F323EB',
//   },
//   {
//     ExId: 4,
//     Id: 12432,
//     FieldSetId: 0,
//     Name: 'Date',
//     Caption: 'Date',
//     Description: '',
//     IsMultiValue: false,
//     Type: 3,
//     AllowedValuesInterface: [],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: 'B91F6130-CEB4-4C6D-859B-19DCB8A800AD',
//   },
//   {
//     ExId: 4,
//     Id: 12433,
//     FieldSetId: 0,
//     Name: 'Checkbox',
//     Caption: 'Checkbox',
//     Description: '',
//     IsMultiValue: false,
//     Type: 0,
//     AllowedValuesInterface: [],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: '12707495-BE0D-4B8A-BDB7-FB7AB2CD8987',
//   },
//   {
//     ExId: 4,
//     Id: 12434,
//     FieldSetId: 0,
//     Name: 'Yes no',
//     Caption: 'Yes no',
//     Description: '',
//     IsMultiValue: false,
//     Type: 0,
//     AllowedValuesInterface: [],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: '77BB31DB-52F3-4306-9D9B-64F2D26DEC5E',
//   },
//   {
//     ExId: 4,
//     Id: 12435,
//     FieldSetId: 0,
//     Name: 'Yes - no non boolean',
//     Caption: 'Yes - no non boolean',
//     Description: '',
//     IsMultiValue: false,
//     Type: 5,
//     AllowedValuesInterface: [],
//     MetaData: null,
//     IsInUse: false,
//     SyncGuid: 'CE66E054-1C23-4235-86ED-0BE5CCE36044',
//   },
// ]
